"""Trilingual public-case and founder-editor interface copy."""

EDITORIAL_COPY = {
    "uz_latn": {
        "cases_kicker": "Avvalo holatlari",
        "cases_title": "Boshqalarning holatlaridan o‘rganing",
        "cases_lead": (
            "To‘lov, havola, ish taklifi va boshqa shubhali vaziyatlarda qaysi belgilarni "
            "ko‘rish va nimani tekshirish kerakligini sodda misollarda tushuntiramiz."
        ),
        "cases_empty": "Hozircha e’lon qilingan holatlar yo‘q.",
        "read_time": "{minutes} daqiqa",
        "read_case": "Tahlilni o‘qish",
        "back_to_cases": "Barcha holatlarga qaytish",
        "article_note": (
            "Bu tahliliy material. U odam yoki tashkilotga hukm bermaydi va sizning "
            "vaziyatingiz bo‘yicha yakuniy xulosa emas."
        ),
        "case_cta_title": "Shunga o‘xshash vaziyat bormi?",
        "case_cta_body": "Matn, havola yoki skrinshotni Avvalo’ga yuborib, tekshiruv rejasini oling.",
        "case_cta_button": "Vaziyatni tekshirish",
        "latest_title": "Yangi holatlar",
        "latest_body": "Haqiqiy hayotga yaqin misollar orqali xavf belgilarini tanishni o‘rganing.",
        "all_cases": "Barcha holatlar",
        "categories": {
            "payments": "To‘lovlar",
            "phishing": "Havola va fishing",
            "marketplace": "Savdo va e’lonlar",
            "jobs": "Ish takliflari",
            "accounts": "Akkauntlar",
            "documents": "Hujjatlar",
        },
        "admin_login_title": "Postlar boshqaruvi",
        "admin_login_body": "Davom etish uchun administrator kalitini kiriting.",
        "admin_key_label": "Administrator kaliti",
        "admin_login_button": "Kirish",
        "admin_login_error": "Kalit noto‘g‘ri. Qayta urinib ko‘ring.",
        "admin_title": "Holatlar va postlar",
        "admin_subtitle": "Uch tildagi tahririy materiallarni yarating va e’lon qiling.",
        "admin_new": "Yangi post",
        "admin_logout": "Chiqish",
        "admin_empty": "Hali postlar yo‘q. Birinchi materialni yarating.",
        "admin_edit": "Tahrirlash",
        "admin_open": "Saytda ochish",
        "admin_updated": "Yangilandi",
        "admin_draft": "Qoralama",
        "admin_published": "E’lon qilingan",
        "form_new_title": "Yangi holat",
        "form_edit_title": "Holatni tahrirlash",
        "form_intro": "Material faqat siz yozgan tahririy matndan tuzilishi kerak.",
        "form_slug": "Sahifa manzili",
        "form_slug_hint": "Lotin harflari, raqamlar va tire: fake-payment-screenshot",
        "form_category": "Turkum",
        "form_state": "Holat",
        "form_translation": "Til versiyalari",
        "form_title": "Sarlavha",
        "form_summary": "Qisqa tavsif",
        "form_article": "Post matni",
        "form_save": "Postni saqlash",
        "form_cancel": "Bekor qilish",
        "form_error": "Barcha maydonlarni tekshiring va qayta saqlang.",
        "duplicate_slug": "Bu sahifa manzili allaqachon ishlatilgan.",
    },
    "uz_cyrl": {
        "cases_kicker": "Avvalo ҳолатлари",
        "cases_title": "Бошқаларнинг ҳолатларидан ўрганинг",
        "cases_lead": (
            "Тўлов, ҳавола, иш таклифи ва бошқа шубҳали вазиятларда қайси белгиларни "
            "кўриш ва нимани текшириш кераклигини содда мисолларда тушунтирамиз."
        ),
        "cases_empty": "Ҳозирча эълон қилинган ҳолатлар йўқ.",
        "read_time": "{minutes} дақиқа",
        "read_case": "Таҳлилни ўқиш",
        "back_to_cases": "Барча ҳолатларга қайтиш",
        "article_note": (
            "Бу таҳлилий материал. У одам ёки ташкилотга ҳукм бермайди ва сизнинг "
            "вазиятингиз бўйича якуний хулоса эмас."
        ),
        "case_cta_title": "Шунга ўхшаш вазият борми?",
        "case_cta_body": "Матн, ҳавола ёки скриншотни Avvalo’га юбориб, текширув режасини олинг.",
        "case_cta_button": "Вазиятни текшириш",
        "latest_title": "Янги ҳолатлар",
        "latest_body": "Ҳаётга яқин мисоллар орқали хавф белгиларини танишни ўрганинг.",
        "all_cases": "Барча ҳолатлар",
        "categories": {
            "payments": "Тўловлар",
            "phishing": "Ҳавола ва фишинг",
            "marketplace": "Савдо ва эълонлар",
            "jobs": "Иш таклифлари",
            "accounts": "Аккаунтлар",
            "documents": "Ҳужжатлар",
        },
        "admin_login_title": "Постлар бошқаруви",
        "admin_login_body": "Давом этиш учун администратор калитини киритинг.",
        "admin_key_label": "Администратор калити",
        "admin_login_button": "Кириш",
        "admin_login_error": "Калит нотўғри. Қайта уриниб кўринг.",
        "admin_title": "Ҳолатлар ва постлар",
        "admin_subtitle": "Уч тилдаги таҳририй материалларни яратинг ва эълон қилинг.",
        "admin_new": "Янги пост",
        "admin_logout": "Чиқиш",
        "admin_empty": "Ҳали постлар йўқ. Биринчи материални яратинг.",
        "admin_edit": "Таҳрирлаш",
        "admin_open": "Сайтда очиш",
        "admin_updated": "Янгиланди",
        "admin_draft": "Қоралама",
        "admin_published": "Эълон қилинган",
        "form_new_title": "Янги ҳолат",
        "form_edit_title": "Ҳолатни таҳрирлаш",
        "form_intro": "Материал фақат сиз ёзган таҳририй матндан тузилиши керак.",
        "form_slug": "Саҳифа манзили",
        "form_slug_hint": "Лотин ҳарфлари, рақамлар ва тире: fake-payment-screenshot",
        "form_category": "Туркум",
        "form_state": "Ҳолат",
        "form_translation": "Тил версиялари",
        "form_title": "Сарлавҳа",
        "form_summary": "Қисқа тавсиф",
        "form_article": "Пост матни",
        "form_save": "Постни сақлаш",
        "form_cancel": "Бекор қилиш",
        "form_error": "Барча майдонларни текширинг ва қайта сақланг.",
        "duplicate_slug": "Бу саҳифа манзили аллақачон ишлатилган.",
    },
    "ru": {
        "cases_kicker": "Кейсы Avvalo",
        "cases_title": "Учитесь на чужих ситуациях",
        "cases_lead": (
            "Разбираем понятные примеры с оплатой, ссылками, вакансиями и другими "
            "сомнительными ситуациями: на что смотреть и что проверять самостоятельно."
        ),
        "cases_empty": "Опубликованных кейсов пока нет.",
        "read_time": "{minutes} мин",
        "read_case": "Читать разбор",
        "back_to_cases": "Вернуться ко всем кейсам",
        "article_note": (
            "Это редакционный разбор. Он не оценивает человека или организацию и не является "
            "окончательным выводом по вашей ситуации."
        ),
        "case_cta_title": "Столкнулись с похожей ситуацией?",
        "case_cta_body": "Отправьте текст, ссылку или скриншот в Avvalo и получите план проверки.",
        "case_cta_button": "Проверить ситуацию",
        "latest_title": "Новые кейсы",
        "latest_body": "Учитесь замечать тревожные признаки на понятных жизненных примерах.",
        "all_cases": "Все кейсы",
        "categories": {
            "payments": "Оплата",
            "phishing": "Ссылки и фишинг",
            "marketplace": "Покупки и объявления",
            "jobs": "Вакансии",
            "accounts": "Аккаунты",
            "documents": "Документы",
        },
        "admin_login_title": "Управление публикациями",
        "admin_login_body": "Введите ключ администратора, чтобы продолжить.",
        "admin_key_label": "Ключ администратора",
        "admin_login_button": "Войти",
        "admin_login_error": "Неверный ключ. Попробуйте ещё раз.",
        "admin_title": "Кейсы и публикации",
        "admin_subtitle": "Создавайте и публикуйте редакционные материалы на трёх языках.",
        "admin_new": "Новый пост",
        "admin_logout": "Выйти",
        "admin_empty": "Публикаций пока нет. Создайте первый материал.",
        "admin_edit": "Редактировать",
        "admin_open": "Открыть на сайте",
        "admin_updated": "Обновлён",
        "admin_draft": "Черновик",
        "admin_published": "Опубликован",
        "form_new_title": "Новый кейс",
        "form_edit_title": "Редактирование кейса",
        "form_intro": "Материал должен состоять только из редакционного текста, написанного вами.",
        "form_slug": "Адрес страницы",
        "form_slug_hint": "Латинские буквы, цифры и дефисы: fake-payment-screenshot",
        "form_category": "Категория",
        "form_state": "Статус",
        "form_translation": "Языковые версии",
        "form_title": "Заголовок",
        "form_summary": "Краткое описание",
        "form_article": "Текст поста",
        "form_save": "Сохранить пост",
        "form_cancel": "Отмена",
        "form_error": "Проверьте все поля и попробуйте сохранить снова.",
        "duplicate_slug": "Такой адрес страницы уже используется.",
    },
}
