"""Bilingual public-case and founder-editor interface copy."""

EDITORIAL_COPY = {
    "uz_latn": {
        "cases_kicker": "Avvalo holatlari",
        "cases_title": "Boshqalarda ishlagan sxemalar",
        "cases_lead": (
            "Qadamma-qadam ko‘rsatamiz: sxema qanday qurilgan va uni qaysi tafsilotdan "
            "oldinroq payqash mumkin."
        ),
        "cases_empty": "Hozircha e’lon qilingan holatlar yo‘q.",
        "read_time": "{minutes} daqiqa",
        "read_case": "Tahlilni o‘qish",
        "back_to_cases": "Barcha holatlarga qaytish",
        "article_note": (
            "Bu Avvalo tahririyati tayyorlagan o‘quv materiali. U foydalanuvchilar "
            "yuborgan ma’lumotlarga asoslanmagan, odam yoki tashkilot haqida dalil bo‘la "
            "olmaydi va sizning vaziyatingiz bo‘yicha yakuniy xulosa bermaydi."
        ),
        "case_cta_title": "Shunga o‘xshash vaziyat bormi?",
        "case_cta_body": (
            "Matn, havola yoki skrinshotni tashlang — sizinikini ko‘rib chiqamiz."
        ),
        "case_cta_button": "Vaziyatni tekshirish",
        "latest_title": "Yangi holatlar",
        "latest_body": "Qisqa tahlillar: nima bo‘lgan va birinchi shubhali belgi qayerda edi.",
        "all_cases": "Barcha holatlar",
        "categories": {
            "payments": "To‘lovlar",
            "phishing": "Havola va fishing",
            "marketplace": "Savdo va e’lonlar",
            "jobs": "Ish takliflari",
            "accounts": "Akkauntlar",
            "documents": "Hujjatlar",
        },
        "admin_login_title": "Postlar boshqaruvi",
        "admin_login_body": "Davom etish uchun administrator kalitini kiriting.",
        "admin_key_label": "Administrator kaliti",
        "admin_login_button": "Kirish",
        "admin_login_error": "Kalit noto‘g‘ri. Qayta urinib ko‘ring.",
        "admin_title": "Holatlar va postlar",
        "admin_subtitle": "Ikki tildagi tahririy materiallarni yarating va e’lon qiling.",
        "admin_new": "Yangi post",
        "admin_logout": "Chiqish",
        "admin_empty": "Hali postlar yo‘q. Birinchi materialni yarating.",
        "admin_edit": "Tahrirlash",
        "admin_open": "Saytda ochish",
        "admin_updated": "Yangilandi",
        "admin_draft": "Qoralama",
        "admin_published": "E’lon qilingan",
        "form_new_title": "Yangi holat",
        "form_edit_title": "Holatni tahrirlash",
        "form_intro": "Material faqat siz yozgan tahririy matndan tuzilishi kerak.",
        "form_slug": "Sahifa manzili",
        "form_slug_hint": "Lotin harflari, raqamlar va tire: fake-payment-screenshot",
        "form_category": "Turkum",
        "form_state": "Holat",
        "form_cover": "Muqova rasmi",
        "form_cover_hint": "JPG, PNG yoki WebP formatidagi rasmni yuklang. Fayl hajmi 10 MB dan oshmasligi kerak.",
        "form_cover_choose": "Rasm tanlash",
        "form_cover_replace": "Boshqa rasm tanlash",
        "form_cover_remove": "Muqova rasmini olib tashlash",
        "form_cover_alt": "Rasm tavsifi",
        "form_translation": "Til versiyalari",
        "form_title": "Sarlavha",
        "form_summary": "Qisqa tavsif",
        "form_article": "Post matni",
        "form_save": "Postni saqlash",
        "form_cancel": "Bekor qilish",
        "form_error": "Barcha maydonlarni tekshiring va qayta saqlang.",
        "duplicate_slug": "Bu sahifa manzili allaqachon ishlatilgan.",
        "cover_invalid": "Rasmni o‘qib bo‘lmadi. JPG, PNG yoki WebP faylini tanlang.",
        "cover_too_large": "Rasm juda katta. 10 MB dan kichik faylni tanlang.",
        "cover_alt_required": "Muqova rasmi uchun ikki tilda qisqa tavsif yozing.",
        "cover_alt_too_long": "Rasm tavsifi 240 belgidan oshmasligi kerak.",
        "cover_alt_without_image": "Avval muqova rasmini tanlang yoki tavsiflarni tozalang.",
    },
    "ru": {
        "cases_kicker": "Кейсы Avvalo",
        "cases_title": "Схемы, которые уже сработали на других",
        "cases_lead": (
            "Разбираем по шагам: как устроена схема и по какой детали её видно "
            "заранее."
        ),
        "cases_empty": "Опубликованных кейсов пока нет.",
        "read_time": "{minutes} мин",
        "read_case": "Читать разбор",
        "back_to_cases": "Вернуться ко всем кейсам",
        "article_note": (
            "Материал подготовлен редакцией Avvalo. Он не основан на пользовательских "
            "проверках, ничего не доказывает о человеке или организации и не даёт "
            "окончательного вывода по вашей ситуации."
        ),
        "case_cta_title": "Столкнулись с похожей ситуацией?",
        "case_cta_body": (
            "Скиньте текст, ссылку или скрин — разберём вашу."
        ),
        "case_cta_button": "Проверить ситуацию",
        "latest_title": "Новые кейсы",
        "latest_body": "Короткие разборы: что произошло и где был первый тревожный сигнал.",
        "all_cases": "Все кейсы",
        "categories": {
            "payments": "Оплата",
            "phishing": "Ссылки и фишинг",
            "marketplace": "Покупки и объявления",
            "jobs": "Вакансии",
            "accounts": "Аккаунты",
            "documents": "Документы",
        },
        "admin_login_title": "Управление публикациями",
        "admin_login_body": "Введите ключ администратора, чтобы продолжить.",
        "admin_key_label": "Ключ администратора",
        "admin_login_button": "Войти",
        "admin_login_error": "Неверный ключ. Попробуйте ещё раз.",
        "admin_title": "Кейсы и публикации",
        "admin_subtitle": "Создавайте и публикуйте редакционные материалы на двух языках.",
        "admin_new": "Новый пост",
        "admin_logout": "Выйти",
        "admin_empty": "Публикаций пока нет. Создайте первый материал.",
        "admin_edit": "Редактировать",
        "admin_open": "Открыть на сайте",
        "admin_updated": "Обновлён",
        "admin_draft": "Черновик",
        "admin_published": "Опубликован",
        "form_new_title": "Новый кейс",
        "form_edit_title": "Редактирование кейса",
        "form_intro": "Материал должен состоять только из редакционного текста, написанного вами.",
        "form_slug": "Адрес страницы",
        "form_slug_hint": "Латинские буквы, цифры и дефисы: fake-payment-screenshot",
        "form_category": "Категория",
        "form_state": "Статус",
        "form_cover": "Обложка",
        "form_cover_hint": "Загрузите фото в формате JPG, PNG или WebP размером до 10 МБ.",
        "form_cover_choose": "Выбрать фото",
        "form_cover_replace": "Выбрать другое фото",
        "form_cover_remove": "Удалить обложку",
        "form_cover_alt": "Описание изображения",
        "form_translation": "Языковые версии",
        "form_title": "Заголовок",
        "form_summary": "Краткое описание",
        "form_article": "Текст поста",
        "form_save": "Сохранить пост",
        "form_cancel": "Отмена",
        "form_error": "Проверьте все поля и попробуйте сохранить снова.",
        "duplicate_slug": "Такой адрес страницы уже используется.",
        "cover_invalid": "Не удалось прочитать изображение. Выберите файл JPG, PNG или WebP.",
        "cover_too_large": "Изображение слишком большое. Выберите файл меньше 10 МБ.",
        "cover_alt_required": "Добавьте краткое описание обложки на двух языках.",
        "cover_alt_too_long": "Описание изображения не должно превышать 240 символов.",
        "cover_alt_without_image": "Сначала выберите обложку или очистите описания.",
    },
}
