"""Trilingual copy for the operator-only knowledge card editor.

The card bodies themselves stay English — they are handed to the model as
guidance and never shown to a user verbatim. Only this interface is trilingual.
"""

# ruff: noqa: E501, RUF001

_ERRORS = {
    "uz_latn": {
        "invalid_face": "Noma'lum tekshiruv yuzasi.",
        "invalid_card_id": "Karta ID'si `family.nom` ko'rinishida bo'lishi kerak.",
        "invalid_card_version": "Versiya noto'g'ri (masalan: 1.0.0).",
        "invalid_status": "Holat approved, draft yoki retired bo'lishi kerak.",
        "invalid_reviewer": "Ko'rib chiquvchi nomi bo'sh bo'lmasin.",
        "invalid_mechanism": "Mexanizm bo'sh bo'lmasligi va 600 belgidan oshmasligi kerak.",
        "invalid_trigger_rule": "Qoida ID'si noto'g'ri (masalan: fs.credential.otp).",
        "invalid_trigger_signal": "Signal turi noto'g'ri.",
        "invalid_reviewed_case": "Ko'rib chiqilgan holat ID'si noto'g'ri.",
        "invalid_aliases": "Qidiruv iboralari ro'yxati noto'g'ri.",
        "invalid_alias_language": "Faqat uz_latn, uz_cyrl va ru tillari qo'llab-quvvatlanadi.",
        "invalid_red_flags": "Belgilar ro'yxati noto'g'ri (eng ko'pi 12 ta, har biri 400 belgigacha).",
        "invalid_verify_steps": "Tekshirish qadamlari ro'yxati noto'g'ri.",
        "invalid_questions": "Savollar ro'yxati noto'g'ri.",
        "duplicate_card": "Bu karta ID'si allaqachon mavjud.",
    },
    "uz_cyrl": {
        "invalid_face": "Номаълум текширув юзаси.",
        "invalid_card_id": "Карта ID'си `family.ном` кўринишида бўлиши керак.",
        "invalid_card_version": "Версия нотўғри (масалан: 1.0.0).",
        "invalid_status": "Ҳолат approved, draft ёки retired бўлиши керак.",
        "invalid_reviewer": "Кўриб чиқувчи номи бўш бўлмасин.",
        "invalid_mechanism": "Механизм бўш бўлмаслиги ва 600 белгидан ошмаслиги керак.",
        "invalid_trigger_rule": "Қоида ID'си нотўғри (масалан: fs.credential.otp).",
        "invalid_trigger_signal": "Сигнал тури нотўғри.",
        "invalid_reviewed_case": "Кўриб чиқилган ҳолат ID'си нотўғри.",
        "invalid_aliases": "Қидирув иборалари рўйхати нотўғри.",
        "invalid_alias_language": "Фақат uz_latn, uz_cyrl ва ru тиллари қўллаб-қувватланади.",
        "invalid_red_flags": "Белгилар рўйхати нотўғри (энг кўпи 12 та, ҳар бири 400 белгигача).",
        "invalid_verify_steps": "Текшириш қадамлари рўйхати нотўғри.",
        "invalid_questions": "Саволлар рўйхати нотўғри.",
        "duplicate_card": "Бу карта ID'си аллақачон мавжуд.",
    },
    "ru": {
        "invalid_face": "Неизвестная поверхность проверки.",
        "invalid_card_id": "ID карточки должен быть вида `family.имя`.",
        "invalid_card_version": "Некорректная версия (например: 1.0.0).",
        "invalid_status": "Статус должен быть approved, draft или retired.",
        "invalid_reviewer": "Имя рецензента не должно быть пустым.",
        "invalid_mechanism": "Механизм не должен быть пустым и длиннее 600 символов.",
        "invalid_trigger_rule": "Некорректный ID правила (например: fs.credential.otp).",
        "invalid_trigger_signal": "Некорректный вид сигнала.",
        "invalid_reviewed_case": "Некорректный ID рассмотренного случая.",
        "invalid_aliases": "Некорректный список поисковых фраз.",
        "invalid_alias_language": "Поддерживаются только uz_latn, uz_cyrl и ru.",
        "invalid_red_flags": "Некорректный список признаков (не более 12, каждый до 400 символов).",
        "invalid_verify_steps": "Некорректный список шагов проверки.",
        "invalid_questions": "Некорректный список вопросов.",
        "duplicate_card": "Карточка с таким ID уже существует.",
    },
}

KNOWLEDGE_COPY = {
    "uz_latn": {
        "title": "Bilim kartalari",
        "subtitle": (
            "Kartalar modelga tushuntirish uchun beriladi. Ular ochiq repozitoriyda emas, "
            "ma'lumotlar bazasida saqlanadi va paketdagi asosiy kartalar ustiga ID bo'yicha qo'shiladi."
        ),
        "new": "Yangi karta",
        "empty": "Hozircha qo'shimcha karta yo'q. Tekshiruv paketdagi asosiy kartalar bilan ishlaydi.",
        "edit": "Tahrirlash",
        "delete": "O'chirish",
        "delete_confirm": "Bu kartani o'chirsangiz, paketdagi asosiy karta yana kuchga kiradi.",
        "back": "Ro'yxatga qaytish",
        "save": "Saqlash",
        "test": "Sinab ko'rish",
        "updated": "Yangilandi:",
        "baseline_note": "Paketdagi asosiy kartalar: {count} ta. Faol kartalar: {active} ta.",
        "body_note": "Karta matni ingliz tilida yoziladi — u modelga uzatiladi, foydalanuvchiga ko'rsatilmaydi.",
        "card_id_label": "Karta ID'si",
        "card_id_hint": "Paketdagi mavjud ID kiritilsa, o'sha karta almashtiriladi. Yangi ID yangi karta qo'shadi.",
        "card_version_label": "Versiya",
        "status_label": "Holat",
        "status_hint": "Faqat `approved` kartalar tanlanadi. `draft` va `retired` shu ID'li asosiy kartani ham o'chiradi.",
        "reviewer_label": "Ko'rib chiquvchi",
        "mechanism_label": "Mexanizm (ingliz tilida)",
        "trigger_rules_label": "Ishga tushiruvchi qoida ID'lari",
        "trigger_signals_label": "Ishga tushiruvchi signal turlari",
        "aliases_label": "Qidiruv iboralari — {language}",
        "aliases_hint": "Har bir qatorda bitta ibora. Matnda shu iboralar topilsa, karta tanlanishi mumkin.",
        "red_flags_label": "Belgilar (ingliz tilida)",
        "verify_steps_label": "Tekshirish qadamlari (ingliz tilida)",
        "questions_label": "Savollar (ingliz tilida)",
        "reviewed_cases_label": "Ko'rib chiqilgan holat ID'lari",
        "list_hint": "Har bir qatorda bitta yozuv.",
        "sample_title": "Sinov matni",
        "sample_hint": (
            "Karta to'g'ri yozilgan bo'lsa ham tanlanmasligi mumkin — tanlash qoida ID'lari va "
            "qidiruv iboralari bo'yicha ishlaydi, karta matni bo'yicha emas."
        ),
        "sample_label": "Namuna matn",
        "preview_title": "Sinov natijasi",
        "preview_selected": "Karta tanlandi. Tanlash usuli: {mode}.",
        "preview_not_selected": "Karta tanlanmadi. Ishga tushiruvchi qoida ID'lari yoki qidiruv iboralarini tekshiring.",
        "preview_not_approved": "Karta tanlanmadi, chunki uning holati `approved` emas ({status}). Faqat `approved` kartalar tanlanadi.",
        "preview_others": "Buning o'rniga tanlangan kartalar:",
        "preview_no_others": "Boshqa kartalar tanlanmadi.",
        "errors": _ERRORS["uz_latn"],
    },
    "uz_cyrl": {
        "title": "Билим карталари",
        "subtitle": (
            "Карталар моделга тушунтириш учун берилади. Улар очиқ репозиторийда эмас, "
            "маълумотлар базасида сақланади ва пакетдаги асосий карталар устига ID бўйича қўшилади."
        ),
        "new": "Янги карта",
        "empty": "Ҳозирча қўшимча карта йўқ. Текширув пакетдаги асосий карталар билан ишлайди.",
        "edit": "Таҳрирлаш",
        "delete": "Ўчириш",
        "delete_confirm": "Бу картани ўчирсангиз, пакетдаги асосий карта яна кучга киради.",
        "back": "Рўйхатга қайтиш",
        "save": "Сақлаш",
        "test": "Синаб кўриш",
        "updated": "Янгиланди:",
        "baseline_note": "Пакетдаги асосий карталар: {count} та. Фаол карталар: {active} та.",
        "body_note": "Карта матни инглиз тилида ёзилади — у моделга узатилади, фойдаланувчига кўрсатилмайди.",
        "card_id_label": "Карта ID'си",
        "card_id_hint": "Пакетдаги мавжуд ID киритилса, ўша карта алмаштирилади. Янги ID янги карта қўшади.",
        "card_version_label": "Версия",
        "status_label": "Ҳолат",
        "status_hint": "Фақат `approved` карталар танланади. `draft` ва `retired` шу ID'ли асосий картани ҳам ўчиради.",
        "reviewer_label": "Кўриб чиқувчи",
        "mechanism_label": "Механизм (инглиз тилида)",
        "trigger_rules_label": "Ишга туширувчи қоида ID'лари",
        "trigger_signals_label": "Ишга туширувчи сигнал турлари",
        "aliases_label": "Қидирув иборалари — {language}",
        "aliases_hint": "Ҳар бир қаторда битта ибора. Матнда шу иборалар топилса, карта танланиши мумкин.",
        "red_flags_label": "Белгилар (инглиз тилида)",
        "verify_steps_label": "Текшириш қадамлари (инглиз тилида)",
        "questions_label": "Саволлар (инглиз тилида)",
        "reviewed_cases_label": "Кўриб чиқилган ҳолат ID'лари",
        "list_hint": "Ҳар бир қаторда битта ёзув.",
        "sample_title": "Синов матни",
        "sample_hint": (
            "Карта тўғри ёзилган бўлса ҳам танланмаслиги мумкин — танлаш қоида ID'лари ва "
            "қидирув иборалари бўйича ишлайди, карта матни бўйича эмас."
        ),
        "sample_label": "Намуна матн",
        "preview_title": "Синов натижаси",
        "preview_selected": "Карта танланди. Танлаш усули: {mode}.",
        "preview_not_selected": "Карта танланмади. Ишга туширувчи қоида ID'лари ёки қидирув ибораларини текширинг.",
        "preview_not_approved": "Карта танланмади, чунки унинг ҳолати `approved` эмас ({status}). Фақат `approved` карталар танланади.",
        "preview_others": "Бунинг ўрнига танланган карталар:",
        "preview_no_others": "Бошқа карталар танланмади.",
        "errors": _ERRORS["uz_cyrl"],
    },
    "ru": {
        "title": "Карточки знаний",
        "subtitle": (
            "Карточки передаются модели как пояснение. Они хранятся в базе данных, а не в "
            "открытом репозитории, и накладываются на базовый набор по ID."
        ),
        "new": "Новая карточка",
        "empty": "Пока нет дополнительных карточек. Проверка идёт по базовому набору.",
        "edit": "Редактировать",
        "delete": "Удалить",
        "delete_confirm": "Если удалить эту карточку, снова вступит в силу базовая карточка из набора.",
        "back": "Вернуться к списку",
        "save": "Сохранить",
        "test": "Проверить",
        "updated": "Обновлено:",
        "baseline_note": "Базовых карточек в наборе: {count}. Активных карточек: {active}.",
        "body_note": "Текст карточки пишется по-английски — он передаётся модели и не показывается пользователю.",
        "card_id_label": "ID карточки",
        "card_id_hint": "Существующий ID из набора заменит эту карточку. Новый ID добавит карточку.",
        "card_version_label": "Версия",
        "status_label": "Статус",
        "status_hint": "Выбираются только карточки `approved`. `draft` и `retired` также отключают базовую карточку с этим ID.",
        "reviewer_label": "Рецензент",
        "mechanism_label": "Механизм (по-английски)",
        "trigger_rules_label": "ID правил, запускающих карточку",
        "trigger_signals_label": "Виды сигналов, запускающих карточку",
        "aliases_label": "Поисковые фразы — {language}",
        "aliases_hint": "По одной фразе в строке. Если фраза найдена в тексте, карточка может быть выбрана.",
        "red_flags_label": "Признаки (по-английски)",
        "verify_steps_label": "Шаги проверки (по-английски)",
        "questions_label": "Вопросы (по-английски)",
        "reviewed_cases_label": "ID рассмотренных случаев",
        "list_hint": "По одной записи в строке.",
        "sample_title": "Тестовый текст",
        "sample_hint": (
            "Карточка может быть написана правильно и всё равно не выбираться — выбор идёт по "
            "ID правил и поисковым фразам, а не по тексту карточки."
        ),
        "sample_label": "Пример текста",
        "preview_title": "Результат проверки",
        "preview_selected": "Карточка выбрана. Способ выбора: {mode}.",
        "preview_not_selected": "Карточка не выбрана. Проверьте ID правил и поисковые фразы.",
        "preview_not_approved": "Карточка не выбрана, потому что её статус не `approved` ({status}). Выбираются только карточки `approved`.",
        "preview_others": "Вместо неё выбраны карточки:",
        "preview_no_others": "Другие карточки не выбраны.",
        "errors": _ERRORS["ru"],
    },
}
